version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - streaming_data:/stream
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
  pyspark_processor:
    build:
      context: ./pyspark_processor
      dockerfile: Dockerfile
    env_file:
      - ./.env.spark
    depends_on:
      - db
    ports:
      - "4040:4040"  # Spark UI port (if needed)
      - "5001:5001"  # Flask API port
    volumes:
      - streaming_data:/stream

volumes:
  postgres_data:
  streaming_data:
