@startuml
actor User
participant FlaskApp
queue StreamVolume
participant PysparkApp
database DB
participant DataSource
User -> FlaskApp: process n files
FlaskApp -> DataSource: get file links
DataSource -> FlaskApp: file links
FlaskApp -> StreamVolume: task.csv
FlaskApp -> User: task created
PysparkApp -> StreamVolume: get task.csv
StreamVolume -> PysparkApp: task.csv
loop for each file
    PysparkApp -> DataSource: get file
    DataSource -> PysparkApp: file
    PysparkApp -> PysparkApp: process file
    PysparkApp -> DB: save metadata
end
@enduml
